### ISSUE TITLE
NSLeaf Error

### ISSUE THREAD

**Issue by mgcrons** [noobpk/frida-ios-intercept-api#2]
Application dies and throws error
`NSLeafProxy
message: {'type': 'error', 'description': 'Error: Unable to handle type undefined', 'stack': 'Error: Unable to handle type undefined\n    at readType (frida/node_modules/frida-objc-bridge/index.js:1292)\n    at parseSignature (frida/node_modules/frida-objc-bridge/index.js:1242)\n    at makeMethodInvocationWrapper (frida/node_modules/frida-objc-bridge/index.js:1033)\n    at _ (frida/node_modules/frida-objc-bridge/index.js:557)\n    at get (frida/node_modules/frida-objc-bridge/index.js:402)\n    at <eval> (/script1.js:159)', 'fileName': 'frida/node_modules/frida-objc-bridge/index.js', 'lineNumber': 1292, 'columnNumber': 1}`

**Comment by noobpk** [comment]
You need edit handlers.js. Write your class & method of your application to it .
