### ISSUE TITLE
'TypeError: not a function', 'stack': 'TypeError: not a function

### ISSUE THREAD

**Issue by Gantaronee** [noobpk/frida-ios-intercept-api#3]
errors.log:
2023-05-16 19:10:38,651 - ERROR - [x_x] The application may crash or lose connection.
2023-05-16 19:12:29,232 - ERROR - [x_x] The application may crash or lose connection.

python3.10 burpTracer.py -p: xxxxxxxxxxxx

......
- _tlsSessionCachePrefix
message: {'type': 'error', 'description': 'TypeError: not a function', 'stack': 'TypeError: not a function\n    at onEnter (/script1.js:191)', 'fileName': '/script1.js', 'lineNumber': 191, 'columnNumber': 1}
message: {'type': 'error', 'description': 'TypeError: not a function', 'stack': 'TypeError: not a function\n    at onEnter (/script1.js:191)', 'fileName': '/script1.js', 'lineNumber': 191, 'columnNumber': 1}
   - aggregateAssetDownloadTaskWithURLAsset:mediaSelections:assetTitle:assetArtworkData:options:
message: {'type': 'error', 'description': 'TypeError: not a function', 'stack': 'TypeError: not a function\n    at onEnter (/script1.js:191)', 'fileName': '/script1.js', 'lineNumber': 191, 'columnNumber': 1}
   - assetDownloadTaskWithConfiguration:
[16-05-23 19:12:29] [ERROR] - [x_x] The application may crash or lose connection.

Any Idea?

**Comment by noobpk** [comment]
Hi,
Can you provide me the code at line 191?
